/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <common.h>
#include "project_configuration.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	printf("STM32F407 Driver Development Project\n");

#if(FEATURE_SELECTED == STM32_PRINT_HELLO_WORLD)
	printHelloWorld();
#elif (FEATURE_SELECTED == STM32_COPY_DATA_FROM_FLASH_TO_SRAM)
    copyDataFromFlashToSram();
#else
    printf("STM32F407 Driver Development Project\n");
#endif

    /* Loop forever */
    for(;;);
}
